### PR TITLE
Proj0020 Item group should only contain nodes of a single type

### PR DESCRIPTION
**Pull request by CptWesley**
Analyzer PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers/pull/85

### CODE REVIEW

**Review by LauraXiulan — APPROVED** [review]

**Review by Corniel — CHANGES_REQUESTED** [review]
I think this rule needs some exceptions:

Changing types for instance.

``` XML
<ItemGroup>
  <None Remove="Files\*" />
  <EmbeddedResource Include="Files\*" />
</ItemGroup>
```

So long story short: I like the idea, but we have to think about how to support the exceptions (other then by adding support to suppress a rule).

**Comment by Corniel** [comment]
What about the following exceptions:

* matching Remove/Include paths
* Non-empty label (that should explain why they are in one block)

**Comment by CptWesley** [comment]
@Corniel Updated implementation

**Comment by Corniel** [comment]
I think the exception should be mentioned in the documentation.

**Comment by CptWesley** [comment]
Updated

**Review by Corniel — APPROVED** [review]

**Pull request merged**
